# Generated by Django 3.2.2 on 2021-06-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_drone_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
