# Generated by Django 3.2.2 on 2021-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_simulation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='lat',
            new_name='marque',
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='long',
            new_name='modele',
        ),
        migrations.AddField(
            model_name='drone',
            name='autonomie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drone',
            name='poids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drone',
            name='vitesse',
            field=models.IntegerField(default=0),
        ),
    ]
