# Generated by Django 3.2.2 on 2021-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_auto_20210603_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='bilan',
            field=models.CharField(default='Aucun bilan disponible', max_length=200),
        ),
    ]
